cooperative-votes-api:
  configurations:
    datasource:
      uri: mongodb://neo:matrix@localhost:8080/cooperative-votes-ms
    kafka:
      producer:
        bootstrapServerHost: localhost:9092
        topic: test
    redis:
      host: 127.0.0.1
      port: 6379