cooperative-votes-api:
  configurations:
    datasource:
      uri: mongodb://root:root@localhost:27017/votes-db?authSource=admin
    kafka:
      producer:
        bootstrapServerHost: localhost:9092
        topic: test
    redis:
      host: 127.0.0.1
      port: 6379