server:
  port: 8080

application:
  property1: 100
  property2: 111
  property3: 1010
---
spring:
  profiles: bean1
application:
  property1: 110011

---
spring:
  profiles: bean2
application:
  property2: 100001
