server:
  port: 8080

application:
  property1: "Valor da Propriedade 1"
  property2: "Valor da Propriedade 2"
  property3: "Valor da Propriedade 3"
---
spring:
  profiles: profile1
application:
  property1: "Alterado o valor da Propriedade 1"

---
spring:
  profiles: profile2
application:
  property2: "Alterado o valor da Propriedade 2"
