version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:3.7
    ports:
      - "27017:27017"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  redis:
    container_name: redis
    image: library/redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_dev:
