cooperative-api:
  configurations:
    datasource:
      uri: ~
    kafka:
      producer:
        bootstrapServerHost: ~
        topic: ~
    redis:
      host: ~
      port: ~
application:
  version: @project.version@
server:
  port: 8080
  servlet:
    context-path: /api.cooperative-api
    application-display-name: cooperative-api
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    timeout: 0
    lettuce:
      pool:
        max-active: 50
        min-idle: 5
        max-idle: 50
        max-wait: 1
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: ${cooperative-api.configurations.datasource.uri}
      field-naming-strategy: org.springframework.data.mongodb.core.mapping.SnakeCaseFieldNamingStrategy
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false